base_args: { 'dim': 784 }
constructor: FaissANN
module: src.faiss_int
name: faiss
run_groups:
  base:
    args: [ [ 32, 64, 128, 256, 512, 1024, 2048, 4096, 8192 ] ]
    query_args: [ [ 1, 5, 10, 50, 100, 200 ] ]
  ivfpqfs:
    args: [ [ 512, 1204, 2048, 4096 ] ]
    query_args: [ [ 1, 5, 10, 50, 100, 200 ], [ 0, 10, 100, 1000 ] ]
