base_args: { 'dim': 784, 'num_leaves': 2000, 'num_leaves_to_search': 100, 'reordering_num_neighbors': 100, 'training_sample_size': 250000 }
constructor: ScannANN
module: src.scann_int
name: scann
run_groups:
  float:
    angular:
      args: [ [ 2000 ], [ 0.2 ], [ 2 ], [ dot_product ] ]
      query_args: [ [ [ 1, 30 ], [ 2, 30 ], [ 4, 30 ], [ 8, 30 ], [ 30, 120 ], [ 35, 100 ], [ 40, 80 ], [ 45, 80 ], [ 50, 80 ], [ 55, 95 ], [ 60, 110 ], [ 65, 110 ], [ 75, 110 ], [ 90, 110 ], [ 110, 120 ], [ 130, 150 ], [ 150, 200 ], [ 170, 200 ], [ 200, 300 ], [ 220, 500 ], [ 250, 500 ], [ 310, 300 ], [ 400, 300 ], [ 500, 500 ], [ 800, 1000 ] ] ]
    euclidean:
      args: [ [ 600 ], [ None ], [ 2 ], [ squared_l2 ] ]
      query_args: [ [ [ 4, 40 ], [ 3, 30 ], [ 6, 60 ], [ 8, 74 ], [ 9, 78 ], [ 10, 82 ], [ 11, 85 ], [ 13, 100 ], [ 16, 120 ], [ 20, 140 ], [ 30, 180 ], [ 35, 240 ], [ 50, 360 ] ] ]
